<?php

namespace AppBundle\Repository;

/**
 * AeropuertoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AeropuertoRepository extends LugarRepository
{
}
