<?php

namespace AppBundle\Repository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends PostRepository
{
    public function getAllPublicData(){
        return $this->createQueryBuilder('u')->addSelect('u.texto')->getQuery()->execute();
    }
}
