<?php

namespace AppBundle\Repository;

/**
 * LugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarRepository extends \Doctrine\ORM\EntityRepository
{
}
