<?php

namespace AppBundle\Repository;

/**
 * ServiciosGeneralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosGeneralesRepository extends \Doctrine\ORM\EntityRepository
{
		

}
