<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Lugar;
use AppBundle\Entity\Viaje;

/**
 * ViajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViajeRepository extends ServicioRepository{
	
	public function findAllByOrigenLugar(Lugar $lugarOrigen){
		$lugarOrigenNombre = $lugarOrigen->getNombre();
		$qr = $this->createQueryBuilder('v')
				->join('v.origen', 'o')
				->join('o.lugar', 'l')
				->where('l.nombre = :lugarOrigenNombre')
				->setParameter('lugarOrigenNombre', $lugarOrigenNombre);
			
		return $qr;
	}

	public function findOneSimilarToGiven(Viaje $viaje){
		
		$nombreViaje = $viaje->getNombre();
		
		if($nombreViaje === null)
			$qr = $this->createQueryBuilder('v')
				->join('v.origen', 'o')
				->join('o.lugar', 'l')
				->where('l.nombre = :lugarOrigenNombre')
				->setParameter('lugarOrigenNombre', $lugarOrigenNombre);
			
		return $qr;
	}

	
	
}
